# Generated by Django 3.1.12 on 2024-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
