# Generated by Django 3.1.12 on 2024-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostMaster',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hostMaster',
            },
        ),
        migrations.CreateModel(
            name='loanTypeMaster',
            fields=[
                ('loantypeId', models.AutoField(primary_key=True, serialize=False)),
                ('Lname', models.CharField(max_length=200)),
                ('Intrest', models.CharField(max_length=100)),
            ],
        ),
    ]
