# Generated by Django 5.1.4 on 2025-01-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_viewersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('c_img', models.ImageField(blank=True, upload_to='custpic')),
            ],
        ),
        migrations.CreateModel(
            name='host_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('h_img', models.ImageField(blank=True, upload_to='hostpic')),
            ],
        ),
        migrations.CreateModel(
            name='service_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, unique=True)),
                ('s_image', models.ImageField(blank=True, upload_to='service_img')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('c_img', models.FileField(upload_to='custpic')),
            ],
        ),
    ]
