# Generated by Django 5.1.4 on 2025-01-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cust_master_host_master_service_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_master',
            name='c_img',
        ),
    ]
