# Generated by Django 5.1.4 on 2025-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_service_master_c_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
